FROM php:7.3.1-fpm

LABEL maintainer="yuttasakcom@gmail.com"

RUN apt-get update &&\
    apt-get install -y git

RUN curl -sS https://getcomposer.org/installer | php -- \
    --install-dir=/usr/bin --filename=composer